version: '2'
services:
  web:
    image: tinegroupware/tine:2022
    restart: always
    depends_on:
      - db
      - cache
    environment:
      TINE20_DATABASE_HOST: db
      TINE20_DATABASE_DBNAME: *MYSQL_DATABASE
      TINE20_DATABASE_USERNAME: *MYSQL_USER
      TINE20_DATABASE_PASSWORD: *MYSQL_PASSWORD
      TINE20_DATABASE_TABLEPREFIX: tine_
      TINE20_CACHING_BACKEND: Redis
      TINE20_CACHING_REDIS_HOST: cache
      TINE20_ACTIONQUEUE_HOST: cache
      TINE20_SESSION_BACKEND: Redis
      TINE20_SESSION_HOST: cache
      TINE20_CREDENTIALCACHESHAREDKEY: change_me
      TINE20_SETUPUSER_USERNAME: tine20setup
      TINE20_SETUPUSER_PASSWORD: tine20setup
      ### the url of you tine installation (should be adjusted)
      # TINE20_URL: http://localhost:4000
      ### install+update tine automatically
      # TINE_INSTALL: "true"
      ### needed for auto-install
      # TINE20_ACCEPTED_TERMS_VERSION: 10000
      # TINE20_LOGIN_USERNAME: admin
      # TINE20_LOGIN_PASSWORD: change_me
      ### apps to install - if omitted, all available apps are installed
      # TINE20_APPLICATION_TO_INSTALL: "Addressbook,Felamimail,Calendar,Filemanager"
    volumes:
      - "tine20_files:/var/lib/tine20/files"
    networks:
      - external_network
      - internal_network
    ports:
      - "127.0.0.1:4000:80"

  db:
    image: mariadb:10.6
    command: --max-allowed-packet=209715210
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: &MYSQL_DATABASE tine
      MYSQL_USER: &MYSQL_USER tine
      MYSQL_PASSWORD: &MYSQL_PASSWORD tine
    # use volume for persistent DB
#    volumes:
#      - "/var/lib/mysql:/var/lib/mysql"
    networks:
      - internal_network

  cache:
    image: redis:5.0.5
    restart: always
    networks:
      - internal_network

### other optional services

#  broadcasthub:
#    image: tinegroupware/broadcasthub:0.6
#    networks:
#      - external_network
#      - internal_network
#    ports:
#      - "5001:80"
#    environment:
#      REDIS_URL: redis://cache:6379
#      REDIS_CHANNEL: broadcasthub
#      TINE20_JSON_API_URL: http://localhost
#      AUTH_TIMEOUT: 5000
#      WS_PORT: 80
#      DEBUG: '*'
#      DEBUG_DEFAULT_LOGGING: "on"
#      DEBUG_LOG_TO_FILE: "off"
#      DEBUG_LOG_FILE: ../../stdout.log

#  documentserver:
#    image: onlyoffice/documentserver:latest
#    ports:
#      - "4020:80"
#    environment:
#      JWT_ENABLED: "true"
#      JWT_SECRET: "change_me_also_define_in_tine_cfg"
#    networks:
#      - external_network
#      - internal_network

#  document-preview:
#    image: tinegroupware/document-preview-service:2.1
#    networks:
#      - internal_network
#    ports:
#      - "127.0.0.1:5000:80"

#  clamav:
#    image: tiredofit/clamav
#    container_name: clamav
#    environment:
#      - ZABBIX_HOSTNAME=clamav
#    # need to be created on the host
#    volumes:
#      - "clamav_files:/data"
#    networks:
#      - internal_network

volumes:
  tine20_files:
#  clamav_files:

networks:
  external_network:
  internal_network:
    internal: true
