site_name: tine groupware docs
site_url: https://www.tine-groupware.de
repo_url: https://github.com/tine-groupware/tine

theme:
  name: material
  logo: images/logo.svg
  favicon: images/favicon.png
  palette:

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy
    - navigation.indexes

extra_css:
  - assets/extra.css

extra_javascript:
  - assets/theme-param.js

#nav:
#  - 'User Guide': 'user-guide.md'
#  - 'tine Admins': 'user-guide.md'
#  - 'sys Admins': '/docker/*'
#  - 'Developers': '/bugs/'

markdown_extensions:
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
        - name: pycon3
          lang: pycon
          options:
            python3: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format: "!!python/object/apply:pymdownx.arithmatex.arithmatex_inline_format {kwds: {mode: generic}}"
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - abbr
  - footnotes

hooks:
  - docs/hooks/build_context_map.py
  - docs/hooks/generate_manual_index.py

extra:
  branding:
    title: tine ®
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tine-groupware/tine
      name: tine groupware on Github
    - icon: fontawesome/solid/globe
      link: https://transifex.com/tine
      name: translations on transifex
  version:
    provider: mike
    alias: true
  img_url_desktop: https://tine-screenshots.s3.rz1.metaways.net/main/1080p/
  img_url_mobile: https://tine-screenshots.s3.rz1.metaways.net/main/720p/
  icon_url: https://raw.githubusercontent.com/tine-groupware/icon-set/master/

plugins:
  - search
  - awesome-pages
  - macros
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      languages:
        - build: true
          default: true
          locale: en
          name: English
        - build: true
          default: false
          locale: de
          name: Deutsch
      reconfigure_material: true
      reconfigure_search: true
#  - enumerate-headings:
#      toc_depth: 6
#      strict: true
#      increment_across_pages: true
#      include:
#        - users/manual/*