/*
 * Tine 2.0
 *
 * @license     http://www.gnu.org/licenses/agpl.html AGPL Version 3
 * @author      Cornelius Weiß <c.weiss@metaways.de>
 * @copyright   Copyright (c) 2022 Metaways Infosystems GmbH (http://www.metaways.de)
 */


class convertTsPtWtToTimeSlotExplainer extends Ext.form.TextArea {

    initComponent() {
        this.readOnly = true;
        const app = Tine.Tinebase.appMgr.get('HumanResources');

        this.value = app.i18n._('Prefer working time over project time timesheets on a daily basis.') + "\n\n" +
            app.i18n._('Timesheets generated by the attendance recorders are created on the so-called working time account of the employee\'s division, whereas project time timesheets are booked to the corresponding project time accounts. An employee\'s working time for a given day is calculated by summing up all of their timesheets for that day. If both working time and project time are tracked in parallel, this rule gives preference to working time on a daily basis.') + "\n\n" +
            app.i18n._('If working time is recorded for a given day, only the working time timesheets for that day will be included in the working time calculation.');

        this.supr().initComponent.call(this);
    }
};
Ext.reg('hr-convertTsPtWtToTimeSlotExplainer', convertTsPtWtToTimeSlotExplainer)
Ext.ux.ItemRegistry.registerItem('HumanResources-BLDailyWTReport_ConvertTsPtWtToTimeSlot-RecordForm', {
    height: 150,
    xtype: 'hr-convertTsPtWtToTimeSlotExplainer'
}, 10);