include:
  - local: '/ci/gitlab-ci/abstract_jobs.yml'
  - local: '/ci/ci-config.yml'
  - local: '/ci/gitlab-ci/test_php_jobs.yml'
  - local: '/ci/gitlab-ci/test_js_jobs.yml'
  - local: '/ci/gitlab-ci/test_jobs.yml'
  - local: '/ci/gitlab-ci/merge_customapp.yml'
  - local: '/ci/gitlab-ci/lib.yml'

stages:
  - build
  - test
  - merge

variables:
  CI_IS_CUSTOMAPP: "true"
  # TESTS
  PHP_UNIT_ALL_TESTS_SOURCE_PARALLEL: "false"
  PHP_UNIT_ALL_TESTS_BUILT: "false"
  PHP_UNIT_SERVERTESTS: "false"
  PHP_UNIT_SETUP_TESTS: "false"
  PHP_STAN_ANALYSES: "true"
  CODE_ANALYSIS_PARALLEL_LINT: "true"
  CODE_ANALYSIS_PHPCS: "true"
  JS_E2E_TEST_SOURCE: "false"
  JS_E2E_TEST_FILTER: ""
  PHPUNIT_FILTER: ${CUSTOMAPP_DIR}_
  # TODO activate when it's working for customapps
  #      see #3835[gitlab][ci] CI customapps e2etest ausführen lassen
  JS_E2E_TESTS_SOURCE: "false"

workflow:
  rules:
    # Disable ci pipeline
    - if: $RUN_CI_PIPELINE == "false"
      when: never
    # Do not run pipelines on push for feature branches. Only merge requests should run feature branche pipelines.
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME =~ /(^feat)|(^pu)|(change)/
      when: never
    - when: always
