# add custom / branch specific merge jobs here (merge2-x)
.mergecustom2:
  stage: merge2
  extends: .abstract.merge
  rules:
    - if: $AUTO_MERGE == "never"
      when: never

merge_saas:
  stage: merge3
  extends: .abstract.merge
  variables:
    BASEVERSION: "2022.11"
    CUSTOMER: saas
  script:
    - merge_merge_upwards $BASEVERSION $CUSTOMER/$BASEVERSION-custom
    - merge_merge_upwards $CUSTOMER/$BASEVERSION-custom $CUSTOMER/$BASEVERSION
    - merge_merge_upwards tine20.com/$BASEVERSION-custom $CUSTOMER/$BASEVERSION
    - merge_trigger_next
  rules:
    - if: $AUTO_MERGE_CUSTOMER == "true"
      when: on_success
    - when: never
