# add custom / branch specific merge jobs here (merge2-x)
# TODO is this still needed?
merge_be:
  stage: merge2
  extends: .abstract.merge
  script:
    - merge_merge_upwards $TINE_VERSION_LTS $TINE_VERSION_BE
    - |
      if [ "${TINE_VERSION_BETA}" != "" ];then
        merge_merge_upwards $TINE_VERSION_BE $TINE_VERSION_BETA
        merge_merge_upwards $TINE_VERSION_BETA $TINE_VERSION_NEXT
      else
        merge_merge_upwards $TINE_VERSION_BE $TINE_VERSION_NEXT
      fi
    - merge_trigger_next
  rules:
    - if: $AUTO_MERGE_BE == "true"
      when: on_success
    - when: never

.mergecustom3:
  stage: merge3
  extends: .abstract.merge
  rules:
    - if: $AUTO_MERGE == "never"
      when: never
