# add custom / branch specific merge jobs here (merge2-x)
# TODO is this still needed?
merge_be:
  stage: merge2
  extends: .abstract.merge
  script:
    - merge_trigger_next
  rules:
    - if: $AUTO_MERGE_BE == "true"
      when: on_success
    - when: never

merge_saas:
  stage: merge3
  extends: .abstract.merge
  variables:
    CUSTOMER: saas
  script:
    - merge_merge_upwards 2023.11 saas/2023.11
    - merge_merge_upwards 2024.11 saas/2024.11
    - merge_merge_upwards saas/2023.11 saas/2024.11
    - merge_trigger_next
  rules:
    - if: $AUTO_MERGE_CUSTOMER == "true"
      when: on_success
    - when: never
