deploy-dev-image-to-gitlab:
  extends: .abstract_jobs.docker
  stage: deploy
  script:
    - ${CI_BUILDS_DIR}/${CI_PROJECT_NAMESPACE}/tine20/ci/scripts/push_image_to_gitlab.sh dev
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /deploy-dev-image-to-gitlab/
    - if: $DEPLOY_DEV_IMAGE_TO_GITLAB == "true"
    - if: $PIPELINE_TYPE =~ /build-dev-images/
  timeout: 20m
  interruptible: false
deploy-dev-image-to-gitlab-arm64:
  services:
    - name: ${UTIL_REGISTRY}/docker:20.10.21-dind-r1
      alias: docker
  image: ${UTIL_REGISTRY}/docker:20.10.21-r1
  extends: deploy-dev-image-to-gitlab
  variables:
    IMAGE_TAG_PLATFORM_POSTFIX: -arm64
    IMAGE_TAG: ${CI_PIPELINE_ID}-${PHP_VERSION}-arm64
  tags:
    - arm64
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /deploy-dev-image-to-gitlab-arm64/
    - if: $DEPLOY_DEV_IMAGE_TO_GITLAB_ARM64 == "true"
    - if: $PIPELINE_TYPE =~ /build-dev-images/

deploy-dev-image-to-dockerhub:
  extends: .abstract_jobs.docker
  stage: deploy
  script:
    - !reference [.lib, script]
    - docker_hub_deploy dev dev $(echo $CI_COMMIT_REF_NAME | sed sI/I-Ig)-${PHP_VERSION}${IMAGE_TAG_PLATFORM_POSTFIX}
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /deploy-dev-image-to-dockerhub/
    - if: $DEPLOY_DEV_IMAGE_TO_DOCKERHUB == "true"
    - if: $PIPELINE_TYPE =~ /build-dev-images/
  timeout: 20m
  interruptible: false
deploy-dev-image-to-dockerhub-arm64:
  services:
    - name: ${UTIL_REGISTRY}/docker:20.10.21-dind-r1
      alias: docker
  image: ${UTIL_REGISTRY}/docker:20.10.21-r1
  extends: deploy-dev-image-to-dockerhub
  variables:
    IMAGE_TAG_PLATFORM_POSTFIX: -arm64
    IMAGE_TAG: ${CI_PIPELINE_ID}-${PHP_VERSION}-arm64
  tags:
    - arm64
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /deploy-dev-image-to-dockerhub-arm64/
    - if: $DEPLOY_DEV_IMAGE_TO_DOCKERHUB_ARM64 == "true"
    - if: $PIPELINE_TYPE =~ /build-dev-images/

.deploy-built-image-to-dockerhub:
  extends: .abstract_jobs.docker
  stage: deploy
  script:
    - !reference [.lib, script]
    - docker_hub_deploy_with_tag built tine
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /deploy-built-image-to-dockerhub/
      when: manual
    - if: $CI_COMMIT_TAG
  timeout: 20m
  interruptible: false
deploy-built-image-to-dockerhub:
  extends: .deploy-built-image-to-dockerhub
  rules:
    - if: ($BASE_MAJOR_COMMIT_REF_NAME != "2023.11" && $BASE_MAJOR_COMMIT_REF_NAME != "2024.11") || $CUSTOMER_MAJOR_COMMIT_REF_NAME != ""
      when: never
    - !reference [.deploy-built-image-to-dockerhub, rules]

deploy-customer-image-to-registry:
  extends: .abstract_jobs.docker
  stage: deploy
  script:
    - !reference [.lib, script]
    - docker login --username $CUSTOMER_IMAGE_REGISTRY_USERNAME --password $CUSTOMER_IMAGE_REGISTRY_PASSWORD $CUSTOMER_IMAGE_REGISTRY_REPO
    - docker_registry_release_image built "$CUSTOMER_IMAGE_REGISTRY_REPO" "$DEPLOY_CUSTOMER_IMAGE_TO_REGISTRY_SET_LATEST"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /deploy-customer-image-to-registry/
      when: manual
    - if: $DEPLOY_CUSTOMER_IMAGE_TO_REGISTRY == "true" && $CI_COMMIT_TAG
  timeout: 20m
  interruptible: false

release-to-gitlab:
  extends: .abstract_jobs.docker
  variables:
    GIT_DEPTH: 100
  stage: deploy
  needs:
    - docker_build_packages
  before_script:
    # todo move to docker image
    - wget https://gitlab.com/api/v4/projects/16573099/packages/generic/release-cli/v0.10.0/release-cli-linux-amd64
    - mv release-cli-linux-amd64 /usr/local/bin/release-cli
    - chmod +x /usr/local/bin/release-cli
  script:
    - !reference [.lib, script]
    - release_to_gitlab
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /release-to-gitlab/
      when: manual
    - if: $PIPELINE_TYPE =~ /release-be/
    - if: $PIPELINE_TYPE =~ /release-weekly/
    - if: $PIPELINE_TYPE =~ /release-monthly/
    - if: $PIPELINE_TYPE =~ /release-customer/
  timeout: 20m
  interruptible: true

release-packages-to-vpackages:
  extends: .abstract_jobs.docker
  stage: deploy
  before_script:
    - apk add openssh
    - eval $(ssh-agent -s)
    - echo "$VPACKAGES_DEPLOY_KEY" | tr -d '\r' | ssh-add -
  script:
    - !reference [.lib, script]
    - release_packages_vpackages_push
    - if [ "$CREATE_CURRENT_LINK" == "true" ]; then release_packages_vpackages_create_current_link; fi
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /release-packages-to-vpackages/
      when: manual
    - if: $PIPELINE_TYPE =~ /release-be/ && $BASE_MAJOR_COMMIT_REF_NAME == "2023.11"
      variables:
        CREATE_CURRENT_LINK: "true"
    - if: $PIPELINE_TYPE =~ /release-be/
    - if: $PIPELINE_TYPE =~ /release-customer/ && $PUSH_TO_VPACKAGES == "true"
  timeout: 20m
  interruptible: false

release-packages-to-gitlab:
  extends: .abstract_jobs.docker          
  stage: deploy
  script:
    - !reference [.lib, script]
    - release_packages_gitlab_set_current_link
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /release-packages-to-gitlab/
      when: manual
    - if: $PIPELINE_TYPE =~ /release-be/ && $BASE_MAJOR_COMMIT_REF_NAME == "2023.11"
    # - if: $PIPELINE_TYPE =~ /release-be/ packages where already pushed by the build, here only the current link is updated
    - if: $PIPELINE_TYPE =~ /release-customer/
  timeout: 20m
  interruptible: false

release-packages-to-github:
  extends: .abstract_jobs.docker
  stage: deploy
  script:
    - !reference [.lib, script]
    - release_packages_github_create_release
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /release-packages-to-github/
      when: manual
    - if: $PIPELINE_TYPE =~ /release-be/ && $BASE_MAJOR_COMMIT_REF_NAME == "2023.11"
    - if: $PIPELINE_TYPE =~ /release-weekly/
  timeout: 20m
  interruptible: false

trigger-release:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  image: ${UTIL_REGISTRY}/docker:19.03.1-r3
  needs: []
  script:
    - !reference [.lib, script]
    - release_tag
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /trigger-release/
    - if: $TRIGGER_RELEASE == "false"
      when: never
    - if: $TRIGGER_RELEASE == "true"
    - if: $PIPELINE_TYPE =~ /trigger-release/
  timeout: 20m
  interruptible: false

update-version-check:
  stage: deploy
  variables:
    TRIGGER_JOBS: update-version
    PACKAGE_STRING: ${CI_COMMIT_TAG}
    CODE_NAME: ${CODENAME}
  trigger:
    project: tine20/versionCheck
    strategy: depend
    branch: master
  rules:
    - if: $CI_COMMIT_TAG && $MAJOR_COMMIT_REF_NAME == "2023.11"

push-test-image-to-gitlab:
  extends: .abstract_jobs.docker
  stage: deploy
  script:
    - ${CI_BUILDS_DIR}/${CI_PROJECT_NAMESPACE}/tine20/ci/scripts/push_image_to_gitlab.sh test
  rules:
    - if: $PUSH_TEST_IMAGE_TO_GITLAB == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /push-test-image-to-gitlab/ 
    - if: $PIPELINE_TYPE =~ /build-test-images/
  timeout: 20m
  interruptible: false
  parallel:
    matrix:
      - PHP_VERSION:
          - "7.4"
          - "8.0"
          - "8.1"