housekeeping-uninterruptible:
  variables:
    KUBERNETES_CPU_REQUEST: 10m
    KUBERNETES_MEMORY_REQUEST: 100Mi
    GIT_STRATEGY: none
  stage: build1
  interruptible: false
  allow_failure: true
  script:
    - >-
      echo "This job dose not build anything.";
      echo "Its is only here to make the pipeline uninterruptible.";
      echo "This job should not run for merge requests and feature branches,";
      echo "but it should run on main branches and for customer apps.";
      echo "";
      echo "gitlab-ci.yml ref:";
      echo "  interruptible:";
      echo "    When Auto-cancel redundant pipelines is enabled, a pipeline is";
      echo "    immediately canceled when a new pipeline starts on the same";
      echo "    branch if either of the following is true:";
      echo "    - All jobs in the pipeline are set as interruptible.";
      echo "    - Any uninterruptible jobs have not started yet.";
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"

# ============ stage: housekeeping ===========================

cache-cleanup:
  image: composer
  stage: housekeeping
  needs: []
  script:
    - !reference [.lib, script]
    - set -x
    - test -f /custom-cache/metrics.sh && /custom-cache/metrics.sh || echo "no metrics script"
    - cache_cleanup_vendor_dir_cache
    - cache_cleanup_npm_dir_cache
    - cache_cleanup_phpstan_cache
    - metrics_lifetime
    - test -f /custom-cache/metrics.sh && /custom-cache/metrics.sh || echo "no metrics script"
  interruptible: false
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /cache-cleanup/
    - if: $PIPELINE_TYPE =~ /cache-cleanup/
    