housekeeping-uninterruptible:
  variables:
    KUBERNETES_CPU_REQUEST: 10m
    KUBERNETES_MEMORY_REQUEST: 100Mi
    GIT_STRATEGY: none
  stage: build1
  interruptible: false
  allow_failure: true
  script:
    - >-
      echo "This job dose not build anything.";
      echo "Its is only here to make the pipeline uninterruptible.";
      echo "This job should not run for merge requests and feature branches,";
      echo "but it should run on main branches and for customer apps.";
      echo "";
      echo "gitlab-ci.yml ref:";
      echo "  interruptible:";
      echo "    When Auto-cancel redundant pipelines is enabled, a pipeline is";
      echo "    immediately canceled when a new pipeline starts on the same";
      echo "    branch if either of the following is true:";
      echo "    - All jobs in the pipeline are set as interruptible.";
      echo "    - Any uninterruptible jobs have not started yet.";
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"

# ============ stage: housekeeping ===========================

docker-populate-cache:
  extends: .abstract_jobs.docker
  stage: housekeeping
  script:
    - !reference [.lib, script]
    - docker_layer_cache_populat_with_hash_image base $(docker_image_hash base) || true
    - ${CI_BUILDS_DIR}/${CI_PROJECT_NAMESPACE}/tine20/ci/scripts/push_image_to_cache.sh source || true
    - ${CI_BUILDS_DIR}/${CI_PROJECT_NAMESPACE}/tine20/ci/scripts/push_image_to_cache.sh test-source || true
    - ${CI_BUILDS_DIR}/${CI_PROJECT_NAMESPACE}/tine20/ci/scripts/push_image_to_cache.sh jsbuild || true
    - ${CI_BUILDS_DIR}/${CI_PROJECT_NAMESPACE}/tine20/ci/scripts/push_image_to_cache.sh build || true
    - ${CI_BUILDS_DIR}/${CI_PROJECT_NAMESPACE}/tine20/ci/scripts/push_image_to_cache.sh built || true
    - ${CI_BUILDS_DIR}/${CI_PROJECT_NAMESPACE}/tine20/ci/scripts/push_image_to_cache.sh test-built || true
    - ${CI_BUILDS_DIR}/${CI_PROJECT_NAMESPACE}/tine20/ci/scripts/push_image_to_cache.sh dev || true
  allow_failure: true # a failure is a problem, but the pipeline should not fail
  interruptible: false
  rules:
    # do not push cache if tests failed
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $RUN_NO_TESTS != "true"
    - if: $PIPELINE_TYPE =~ /default-tests/
    - if: $PIPELINE_TYPE =~ /mr-tests/
    - if: $PIPELINE_TYPE =~ /matrix-tests/

cache-cleanup:
  image: composer
  stage: housekeeping
  needs: []
  script:
    - !reference [.lib, script]
    - set -x
    - cache_cleanup_vendor_dir_cache
    - cache_cleanup_npm_dir_cache
    - cache_cleanup_phpstan_cache
  interruptible: false
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /cache-cleanup/
    - if: $PIPELINE_TYPE =~ /cache-cleanup/
    