.abstract.merge:
  variables:
    GIT_STRATEGY: none
    MERGENONINTERACTIVE: "true" # "false" is also true! Runs not interactive if the variable exists.
    pushOptSkipCi: "true" # "false" is also true! Runs not interactive if the variable exists.
  image: ${TEST_IMAGE}
  needs: []
  tags:
    - custom-cache
  before_script:
    - !reference [.lib, script]
    - cp $DOCKER_GIT_CONFIG ~/.gitconfig
    - git_repo_clone_cached
    - git config --global user.email "gitlabci@metaways.de"
    - git config --global user.name "gitlabci"
    - git_repo_clone_cached ${CI_BUILDS_DIR}/merge
    - cd ${CI_BUILDS_DIR}/merge
    - git config merge.pofile.name "merge po-files driver"
    - git config merge.pofile.driver "${CI_BUILDS_DIR}/${CI_PROJECT_NAMESPACE}/tine20/scripts/git/merge-po-files %A %O %B"
    - git config merge.pofile.recursive "binary"
    - git remote add customers https://gitlab.metaways.net/tine20/tine20.git
    # TODO remove github.com when github.com/tine20/tine20 is obsolete
    - git remote add github.com https://github.com/tine20/tine20.git
    - git remote add github https://github.com/tine-groupware/tine.git
    - cd ${CI_BUILDS_DIR}/merge/tine20
    
# todo move custom merge to .abstract.merge and then delete this job
.abstract.merge_on_source_image:
  extends: .abstract.merge

include:
  - local: '/ci/gitlab-ci/custom_merge_jobs.yml'

merge:
  stage: merge1
  extends: .abstract.merge
  script:
    - merge_merge_upwards 2022.11 2023.11
    - merge_merge_upwards 2023.11 2024.11
    # BE changes < 2023.11 (TODO remove that when 2022.11 is obsolete)
    - merge_merge_upwards tine20.com/2022.11-custom 2023.11
    - merge_merge_upwards 2023.11 2024.11
    - merge_merge_mirror customers 2024.11 github main
    - merge_merge_mirror github main customers 2024.11
    - merge_trigger_next
  rules:
    - if: $AUTO_MERGE == "never"
      when: never
    - if: $CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_REF_NAME == "2022.11" || $CI_COMMIT_REF_NAME == "2023.11" || $CI_COMMIT_REF_NAME == "2024.11" ||  $CI_COMMIT_REF_NAME == "tine20.com/2022.11-custom")
      variables:
        AUTO_MERGE_VAR: "true"
    - if: $AUTO_MERGE == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /auto_merge/
    - if: $PIPELINE_TYPE =~ /auto-merge/